### ISSUE TITLE
Cannot install haskelldb-hdbc-2.2.2 with GHC-7.10.1

### ISSUE THREAD

**Issue by PaulJohnson** [m4dc4p/haskelldb#26]
$ cabal install haskelldb-hdbc
    Resolving dependencies...
    Configuring haskelldb-hdbc-2.2.2...
    Building haskelldb-hdbc-2.2.2...
    Preprocessing library haskelldb-hdbc-2.2.2...

    on the commandline: Warning:
        -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS
    [1 of 1] Compiling Database.HaskellDB.HDBC ( Database/HaskellDB/HDBC.hs, dist/dist-sandbox-9c40b1cf/build/Database/HaskellDB/HDBC.o )
    
    Database/HaskellDB/HDBC.hs:214:1:
        Non type-variable argument
          in the constraint: Data.Convertible.Base.Convertible SqlValue r
        (Use FlexibleContexts to permit this)
        When checking that ‘hdbcGetValue’ has the inferred type
          hdbcGetValue :: forall (m :: * -> *) r.
                          (Monad m, Data.Convertible.Base.Convertible SqlValue r) =>
                          Map String SqlValue -> String -> m r
    Failed to install haskelldb-hdbc-2.2.2
    cabal: Error: some packages failed to install:
    haskelldb-hdbc-2.2.2 failed during the building phase. The exception was:
    ExitFailure 1

**Comment by m4dc4p** [comment]
If you can submit a patch I'd be glad to apply it. Bonus points if its backwards compatible with GHC 7.8.

**Comment by PaulJohnson** [comment]
Inserting this at the top of HDBC.hs lets it compile for GHC 7.10. I expect it will work with 7.8 as well, but I don't have it installed to test with.

    {-# Language FlexibleContexts #-}

I got test-hdbc-postgresql running (TestCases.hs also needs FlexibleContexts) and got 10 errors. Visual inspection showed that the only difference between expected and actual was that spurious brackets are no longer being included in expressions. I don't think this has anything to do with the change.

Paul.

**Comment by nomeata** [comment]
I would appreciate a release with this fix.

**Comment by m4dc4p** [comment]
HaskellDB-HDBC 2.2.4 released with this fix:

  http://hackage.haskell.org/package/haskelldb-hdbc

(See https://github.com/m4dc4p/haskelldb/tree/v2.2.4)
