### ISSUE TITLE
Build errors - lts >= 7

### ISSUE THREAD

**Issue by kanishka-azimi** [m4dc4p/haskelldb#27]
I can build with stack lts <= 6. I will try to paste the build errors here eventually. It might be a minor change to fix?

```
[ 8 of 27] Compiling Database.HaskellDB.BoundedList ( src/Database/HaskellDB/BoundedList.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/Database/HaskellDB/BoundedList.o )

/home/mackey/mackeyhackage/haskelldb/src/Database/HaskellDB/BoundedList.hs:104:10: error:
    • Could not deduce (Size a)
        arising from the superclasses of an instance declaration
      from the context: Less a N1
        bound by the instance declaration
        at src/Database/HaskellDB/BoundedList.hs:104:10-31
      Possible fix:
        add (Size a) to the context of the instance declaration
    • In the instance declaration for ‘Less a N2’
```

**Comment by m4dc4p** [comment]
I'm glad to accept a pull request but I probably won't be able to fix
myself.

**Comment by tomjaguarpaw** [comment]
@kanishka-azimi HaskellDB has been bitrotting for years.  Is there a reason [Opaleye](https://github.com/tomjaguarpaw/haskell-opaleye).

**Comment by kanishka-azimi** [comment]
I was going to switch to opaleye's Haskelldb soon. I thought I would note
this, to see if we can get it building for others before I switch.

**Comment by kanishka-azimi** [comment]
I don't mind what happens with respect to this issue, but leaving this as documentation for future developers who might attempt the same.

**Comment by m4dc4p** [comment]
I'm not familiar with stack's LTS packages; could you paste the .cabal file used, so I can see all versions that caused the problem? (I assume it's got something to do with a newer GHC and the version of `base` should tell me that).

Thanks!

**Comment by kanishka-azimi** [comment]
https://www.stackage.org/nightly-2017-03-31/cabal.config?global=true

That's the long answer. I don't know the fastest way to get stack to dump
the subset of library versions for a particular build. I know people have
made helpers like Jenga recently.

**Comment by kanishka-azimi** [comment]
More detailed information:

````
$ stack list-dependencies
array 0.5.1.1
base 4.9.1.0
bytestring 0.10.8.1
containers 0.5.7.1
deepseq 1.4.2.0
directory 1.3.0.0
filepath 1.4.1.1
ghc-prim 0.5.0.0
haskelldb 2.2.4
integer-gmp 1.0.0.1
mtl 2.2.1
old-locale 1.0.0.7
old-time 1.1.0.3
pretty 1.1.3.3
time 1.6.0.1
transformers 0.5.2.0
unix 2.7.2.1
```

**Comment by kanishka-azimi** [comment]
You can reopen when this is active or if another developer attempts to build this project.
